[package]
name = "cloudbbq2-rs"
version = "0.1.0"
authors = ["Rüdiger Sonderfeld <ruediger@c-plusplus.net>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ruediger/cloudbbq2-rs"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff = { version = "0.2.1", features = ["tokio"] }
bluez-generated = { version = "0.2.1" }
dbus = { version = "0.9.1", features = ["futures"] }
dbus-tokio = "0.7.3"
futures = "0.3.9"
itertools = "0.10.0"
log = "0.4.11"
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["macros", "rt", "rt-multi-thread"] }
