name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required Ubuntu packages
        run: sudo apt install -y libdbus-1-dev pkg-config libdbus-1-3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

